implemented the interface
amosproj/amos2023ws03-gui-frame-diff pull request #132
Opened 2023-12-07 14:07 UTC by a-miscellaneous

- [x] extend matching types to include perfect matches
- [x] implement showing pictures
- [x] implement init with fake sequence fetching
- [x] implemented init with real sequence fetching
- [x] implemented frame jumping
- [x] bound buttons to execute frame jumping
- [x] implemented difference jumping + bind to buttons
- [x] transfer paths from selectionScreen to differenceScreen
- [x] made all screens proportional
- [x] created a basic ugly Theme
- [x] added keyboard navigation 

NEW TICKET:
extend testCaseGenerator to generate Matches and PERFECTS
choose better color scheme

2023-12-09 10:36 UTC, akriese commented
There is quite a lot to this PR. Some things I would not consider part of the actual ticket, e.g. UI changes and changes to the DifferenceGenerator subproject. Would it be possible to take these changes and put them into a separate PR to better review this one? Because I dont really know where to start here as so many different things are happening

2023-12-11 10:57 UTC, simonsasse requested changes
This is really a huge step for the GUI ! Thank you for your effort :)
There are some things though, the documentation, some naming stuff and the TestCaseGenerator. And also it would be nice to have a cleaner commit history I guess.

2023-12-11 10:57 UTC, simonsasse commented on DifferenceGenerator/src/main/kotlin/algorithms/AlignmentAlgorithm.kt
please adjust the documentation of the Alignment element and add the new option PERFECT

2023-12-11 10:57 UTC, simonsasse commented on DifferenceGenerator/src/main/kotlin/algorithms/Gotoh.kt
> -            traceback.add(origin)
// check indices

2023-12-11 10:57 UTC, simonsasse commented on GUI/src/main/kotlin/frameNavigation/FrameNavigation.kt
Would be nice to have some documentation for the functions and the class.

2023-12-11 10:57 UTC, simonsasse commented on GUI/src/main/kotlin/frameNavigation/FrameNavigation.kt
> +    override fun jumpToNextDiff(forward: Boolean) {
I think forward should be defaulted to true.

2023-12-11 10:57 UTC, simonsasse commented on GUI/src/main/kotlin/logic/differenceGeneratorWrapper/DifferenceGeneratorWrapper.kt
> +    fun getSequence(): Array<AlignmentElement> {
add small documentation.

2023-12-11 10:57 UTC, simonsasse commented on GUI/src/main/kotlin/ui/components/AutoSizeText.kt
> +// Reimplements the Text composable with auto-sizing functionality.
Use: 
/** SOME DOC
*
*/

So it will be displayed if you hover over an element in the IDE :)

2023-12-11 10:57 UTC, simonsasse commented on GUI/src/main/kotlin/ui/components/FileSelectorButton.kt
>  * @param onUpdateResult A function that will be called with the selected file path as a parameter.
add the third @param buttonPath

2023-12-11 10:57 UTC, simonsasse commented on GUI/src/main/kotlin/ui/screens/DiffScreen.kt
>   *
add @params here :)

2023-12-11 10:57 UTC, simonsasse commented on GUI/src/main/kotlin/wrappers/AllVideos.kt
I would name this folder and package "models" or something like that.

2023-12-11 10:59 UTC, simonsasse commented on DifferenceGenerator/src/main/kotlin/algorithms/Gotoh.kt
> +            if (origin == AlignmentElement.MATCH && similarityM[i][j] == 1.0) { // check indexes
// check indices

2023-12-11 13:55 UTC, simonsasse requested changes
tiny CnP error, otherwise LGTM :)

2023-12-11 13:55 UTC, simonsasse commented on GUI/src/main/kotlin/ui/screens/DiffScreen.kt
> + * A Composable function that creates a screen to display the differences between two videos.
I guess some CnP errors. Doc doesn't make much sense.

2023-12-11 13:55 UTC, simonsasse commented on GUI/src/main/kotlin/ui/screens/DiffScreen.kt
> + * A Composable function that creates a screen to display the differences between two videos.
I guess some CnP errors. Doc doesn't make much sense.

2023-12-11 13:55 UTC, simonsasse commented on GUI/src/main/kotlin/ui/screens/DiffScreen.kt
> + * A Composable function that creates a button to jump that jumps frame.
I guess some CnP errors. Doc doesn't make much sense.

2023-12-11 14:02 UTC, simonsasse approved these changes
💯

2023-12-11 19:07 UTC, AlperK61 approved these changes

2023-12-11 19:09 UTC, merged