added global state and refactored to accomodate the state
amosproj/amos2023ws03-gui-frame-diff pull request #153
Opened 2023-12-13 17:15 UTC by a-miscellaneous

2023-12-13 17:28 UTC, akriese commented
@a-miscellaneous could you slide in a small fix into this? When executing the GUI, the preset paths are wrong. They should be test/... instead of main/... :)

2023-12-13 17:30 UTC, akriese commented
Am I right, that the `state.value.copy(args)` args are only what changes in the state change, so that one does not have to write too much code? I yes, this approach seems good enough to me :)

2023-12-13 18:20 UTC, AlperK61 approved these changes
it still woks

2023-12-14 08:55 UTC, simonsasse requested changes
Documentation-Police requests changes. 💅

2023-12-14 08:55 UTC, simonsasse commented on GUI/src/main/kotlin/frameNavigation/FrameNavigation.kt
>   * @param paths [AllVideos] object containing the paths to the videos.
adjust doc

2023-12-14 08:55 UTC, simonsasse commented on GUI/src/main/kotlin/models/AppState.kt
> +
create doc

2023-12-14 08:55 UTC, simonsasse commented on GUI/src/main/kotlin/ui/screens/DiffScreen.kt
>  /**
adjust doc

2023-12-14 08:55 UTC, simonsasse commented on GUI/src/main/kotlin/ui/screens/SelectVideoScreen.kt
>  @Composable
Since you're on it, add doc here as well :)

2023-12-14 10:13 UTC, a-miscellaneous commented
> Am I right, that the `state.value.copy(args)` args are only what changes in the state change, so that one does not have to write too much code when modifying the state? I yes, this approach seems good enough to me :)

yes that is correct

2023-12-14 10:17 UTC, a-miscellaneous commented
lgtm

2023-12-14 10:42 UTC, simonsasse approved these changes

2023-12-14 10:43 UTC, merged