Gui/feature/timeline
amosproj/amos2023ws03-gui-frame-diff pull request #155
Opened 2023-12-14 11:02 UTC by AlperK61

closes #110

2023-12-14 11:43 UTC, akriese commented
Can you rebase this onto the current main and resolve conflicts? Then the CI will be able to run :)

2023-12-14 12:04 UTC, akriese commented
Tried it out and it looks pretty nice to me! Good work :)
One thing that I would change is the red stroke jumping to the actual percentage of the closest frame.
So, if there are 10 images, I click at 54%, it should directly go to 50%. What do you think?

2023-12-16 14:47 UTC, akriese requested changes

2023-12-16 14:47 UTC, akriese commented on GUI/src/main/kotlin/Timeline.kt
> +            var helper = Offset.Zero
Could you rename this variable to a more descriptive one? I think, it is used to store the actual mouse position, so maybe `mousePosition`?

2023-12-16 14:47 UTC, akriese commented on GUI/src/main/kotlin/Timeline.kt
> +import androidx.compose.foundation.Canvas
I think this file should be placed in the ui/components/ folder to stick with the current file tree scheme

2023-12-18 11:45 UTC, simonsasse requested changes
Works fine and code looks good :) Only one thing, composable are usually not wrapped in a class.

2023-12-18 11:45 UTC, simonsasse commented on GUI/src/main/kotlin/ui/components/Timeline.kt
> +class Timeline {
I think usually one does not wrap composeables into a class. I suggest removing the `class Timeline` and renaming the `fun timeline` to `fun Timeline`.

2023-12-18 12:52 UTC, simonsasse approved these changes
LGTM :)

2023-12-18 13:18 UTC, akriese approved these changes

2023-12-18 14:32 UTC, merged