refactor(lib1): move library up a directory
amosproj/amos2023ws03-gui-frame-diff pull request #156
Opened 2023-12-14 13:53 UTC by akriese

2023-12-14 13:58 UTC, akriese commented
Converting to draft while waiting for #150

2023-12-18 09:42 UTC, zino212 requested changes

2023-12-18 09:42 UTC, zino212 commented on VideoGenerator/src/resources/Screenshot_50.png
Can you maybe remove these three screenshots? I initially added them to test the video generator, but I think we don't need them anymore.

2023-12-18 09:54 UTC, akriese commented on VideoGenerator/src/resources/Screenshot_50.png
They are being used by a test though

2023-12-19 11:28 UTC, zino212 approved these changes

2023-12-19 11:28 UTC, merged