added settings screen
amosproj/amos2023ws03-gui-frame-diff pull request #157
Opened 2023-12-14 14:39 UTC by a-miscellaneous

added button to go to difference screen
added button to save in difference screen
added sliders
added mask selection

TODO: better design

2023-12-14 15:16 UTC, akriese requested changes

2023-12-14 15:16 UTC, akriese commented on GUI/src/main/kotlin/models/AppState.kt
> +    var gapOpenPenalty: Double = 0.3,
These defaults are different from what was determined in https://github.com/amosproj/amos2023ws03-gui-frame-diff/pull/137.

2023-12-14 15:16 UTC, akriese commented on GUI/src/main/kotlin/ui/screens/SettingsScreen.kt
> +                title = "Gap Extend Penalty",
For consistency reasons we should call this gapExtensionPenalty as in lib2.

2023-12-14 15:16 UTC, akriese commented on GUI/src/main/kotlin/ui/screens/SettingsScreen.kt
> +                buttonText = "Upload  Mask",
two spaces between words

2023-12-15 10:53 UTC, akriese approved these changes

2023-12-15 14:19 UTC, akriese commented
Please wait for decision on adding text input for the parameters before merging :)

2023-12-15 16:03 UTC, AlperK61 commented
ok, please notify me

2023-12-17 11:05 UTC, merged