Add info icons
amosproj/amos2023ws03-gui-frame-diff pull request #183
Opened 2023-12-27 19:19 UTC by zino212

Closes #172

2023-12-30 19:50 UTC, zino212 commented
In my opinion, the at least the settings screen needs to be refactored. There are some adjustments to be made but they are not part of this ticket.
 The sizes and scales of the various components are not optimized.

2024-01-05 22:58 UTC, a-miscellaneous requested changes
minor changes.
the styling needs to be fixed, probably part of another ticket?

2024-01-05 22:58 UTC, a-miscellaneous commented on GUI/src/main/kotlin/ui/screens/SettingsScreen.kt
> +                },
onliners are more readable imo:
.onPointerEvent(PointerEventType.Enter) { isHovered = true }

2024-01-05 22:58 UTC, a-miscellaneous commented on GUI/src/main/kotlin/ui/screens/SettingsScreen.kt
> +        )
one-line

2024-01-08 17:24 UTC, akriese commented
I fixed the space between titles and tooltip icons, but the tooltips for buttons are still an issue. Will look into that tomorrow :)

2024-01-09 15:22 UTC, akriese commented
rebased on most recent main

2024-01-09 17:03 UTC, a-miscellaneous requested changes
i don't see tooltips?
![image](https://github.com/amosproj/amos2023ws03-gui-frame-diff/assets/96189996/54286cb7-5c25-4428-a6a9-362edbd41cc3)

2024-01-09 17:03 UTC, a-miscellaneous commented on GUI/src/main/kotlin/ui/screens/SettingsScreen.kt
> +            "and the area with black rectangles will not be included in the computation."
technically wrong:
Upload a png with a clear background and colored areas.\n" +
            "The clear areas will be included in the video difference computation \n" +
            "and the area with colored in will not be included in the computation

2024-01-10 02:02 UTC, akriese commented
rebased after merge of #184

2024-01-10 09:10 UTC, a-miscellaneous approved these changes
LGTM

2024-01-10 09:10 UTC, merged