Gui/feature/manaual saving frame as png
amosproj/amos2023ws03-gui-frame-diff pull request #184
Opened 2024-01-06 11:59 UTC by AlperK61

<img width="502" alt="image" src="https://github.com/amosproj/amos2023ws03-gui-frame-diff/assets/92909013/48b9a126-c283-4913-850b-760c8b7f06d0">

2024-01-09 10:15 UTC, simonsasse commented
I assigned someone else for review because @zino212 is not available I think.

2024-01-09 10:22 UTC, simonsasse requested changes
please rebase :)

2024-01-09 10:22 UTC, simonsasse commented on GUI/src/main/kotlin/ui/components/FileSelectorButton.kt
> +    val result = fileChooser.showOpenDialog(null)
I found out that on Mac you cannot Save to a non existing file, because I cannot name it. Please use `fileChooser.showSaveDialog(null)`.

2024-01-10 01:56 UTC, akriese approved these changes

2024-01-10 01:57 UTC, merged