loading spinner
amosproj/amos2023ws03-gui-frame-diff pull request #232
Opened 2024-01-22 18:29 UTC by AlperK61

closes #208

2024-01-23 10:04 UTC, a-miscellaneous requested changes

2024-01-23 10:06 UTC, a-miscellaneous commented
generating differences is sadly not cancelable, job.cancel does not work.
parentJob lauch generation and then parentjob.cancel also does not work

2024-01-23 16:57 UTC, akriese commented
What do we do with this then? @a-miscellaneous @AlperK61

2024-01-24 09:34 UTC, a-miscellaneous commented
> What do we do with this then? @a-miscellaneous @AlperK61

next sprint, conflicts left

2024-01-24 16:47 UTC, akriese commented
We have to make the difference generation cooperative for cancelling. Then, `job.cancel()` will work. I'll look into that now

2024-01-24 17:13 UTC, akriese commented
After doing my research, it is pretty clear, that we can only cancel the job by injecting some kind of suspend function into the `Algorithm.run()` or some check if the job is still wanted. That would mean needing to refactor lib2 quite a bit so that it is cancel-aware... Unfortunately, the builtin `Threat.yield()` does not work as `kotlinx.coroutines.yield` and thus, lib2 must include kotlinx somehow.
Or... We redefine the algorithm to run in steps, like a ML training. Then, we could check if the job was cancelled between each step.
Some links I checked:
https://stackoverflow.com/questions/69097765/how-to-stop-or-cancel-a-kotlin-coroutine-stop-currently-running-code-block-inst
https://stackoverflow.com/questions/74065990/properly-cancelling-kotlin-coroutine-job

2024-01-25 17:10 UTC, akriese commented
Rebased onto main and added singleton to cancel running algorithm instance.

2024-01-26 15:37 UTC, zino212 requested changes
LGTM and seems to work nicely. I only request using the Material 3 Colorscheme and Fonts for the Dialog

2024-01-26 15:37 UTC, zino212 commented on GUI/src/main/kotlin/ui/components/selectVideoScreen/LoadingDialog.kt
> +    AlertDialog(
The other AlertDialogs we use are now styled like this:

![image](https://github.com/amosproj/amos2023ws03-gui-frame-diff/assets/52202194/0714ef02-c6d9-4832-ad2d-f53993da061e)

You can either change that here or is will be done in the design branch after rebasing on this one. If requested I can also change this here.

2024-01-26 16:13 UTC, zino212 approved these changes

2024-01-26 16:32 UTC, merged